# Generated by Django 5.2.1 on 2025-06-03 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_shopinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название мебели')),
                ('image', models.ImageField(upload_to='furniture/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.RenameModel(
            old_name='FlowerShop',
            new_name='Shop',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bouquet',
        ),
        migrations.AddField(
            model_name='order',
            name='furniture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.furniture'),
        ),
        migrations.DeleteModel(
            name='Bouquet',
        ),
    ]
